export {default as Home} from "./Home"
export {default as Measurement} from "./Measurement"
export {default as Description} from "./Description"
export {default as Point} from "./Point"
export {default as Page1} from "./Page1"
export {default as Page2} from "./Page2"